name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Шаг 1: Сборка Docker образа
      - name: Build Docker image
        run: docker build . -t jopoleon/tsm_test:latest

      # Шаг 2: Вход в Docker Hub (если вы используете его для хранения образов)
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Push образа в Docker Hub или другой реестр
      - name: Push Docker image
        run: docker push jopoleon/tsm_test

      # Шаг 4: Деплой на AWS EC2
      # Этот шаг потребует настройки SSH доступа или использования AWS CodeDeploy
      # В качестве примера, здесь показано как выполнять SSH команды
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo docker pull jopoleon/tsm_test:latest
            sudo docker stop tsm_test || true
            sudo docker run --rm -d --name tsm_test -p 80:8080 tsm_test:latest
